In [2]:
import numpy as np

In [3]:
def sig(z):
    return 1 / ( 1+ np.exp(-z))

In [4]:
sig(0)

0.5

In [5]:
def sigp(z):
    return sig(z) * (1 - sig(z))

In [6]:
sigp(0)

0.25

In [14]:
def forward(X , W_and_bias):
    w1 = W_and_bias["w1"]
    w2 = W_and_bias["w2"]
    b1 = W_and_bias["b1"]
    b2 = W_and_bias["b2"]
    z1 = w1 @ X + b1
    A1 = sig(z1)
    z2 = w2 @ A1 + b2
    A2 = sig(z2)
    return {"z1" : z1 , "z2" : z2 , "A1" : A1, "A2" : A2}

In [15]:
def cost(y_hat , y):
    return y_hat - y

In [27]:
def back_and_grad(X , y , W_and_bias , learning_rate , num_ep):
    
    for i in range(num_ep):
    
        cache = forward(X, W_and_bias)
        y_hat = cache["A2"]
        error = cost(y_hat, y)

        delta1 = error * sigp(cache["z2"])
        der_w2 = delta1 @ cache["A1"].T
        der_b2 = np.sum(delta1)

        delta2 = (W_and_bias["w2"].T @ delta1) * sigp(cache["z1"]) 
        der_w1 = delta2 @ X.T 
        der_b = np.sum(delta2, 1 , keepdims = True)

        W_and_bias["w1"] -= learning_rate * der_w1
        W_and_bias["w2"] -= learning_rate * der_w2
        W_and_bias["b1"] -= learning_rate * der_b
        W_and_bias["b2"] -= learning_rate * der_b2
        if( i % (num_ep * .1) == 0):
            print(cache["A2"])
    
W_and_bias = {}
W_and_bias["w2"] = np.random.rand(1,2)
W_and_bias["w1"] = np.random.rand(2,2)
W_and_bias["b2"] = np.random.rand(1)
W_and_bias["b1"] = np.random.rand(2,1)

X = np.array([[1,1,0,0], [1,0,1,0]])
y = np.array([1,0,0,1])
learning_rate = 0.01
num_epoch = 1000000
back_and_grad(X , y , W_and_bias , learning_rate, num_epoch)
    


[[0.87370118 0.85921122 0.86360237 0.84280894]]
[[0.94346297 0.05256438 0.05252369 0.9426691 ]]
[[0.96894053 0.02957568 0.02955892 0.96648472]]
[[0.97653169 0.02252133 0.02251043 0.97417387]]
[[0.98046326 0.01882718 0.01881897 0.97827285]]
[[0.98294973 0.01647593 0.01646929 0.98090795]]
[[0.98469781 0.01481582 0.0148102  0.98278089]]
[[0.98601053 0.01356522 0.01356034 0.98419866]]
[[0.98704178 0.01258036 0.01257603 0.98531936]]
[[0.98787895 0.01177928 0.01177537 0.98623367]]
